### ISSUE TITLE
package mrmarkfrench/silverpop-php-connector could not be found

### ISSUE THREAD

**Issue by rvarbanov** [mrmarkfrench/silverpop-php-connector#19]
Hey,

Today I tried installing your package with composer and got this:
```
  Problem 1
    - The requested package mrmarkfrench/silverpop-php-connector could not be found in any version, there may be a typo in the package name.


Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
```

Here is my composer.json:
```
{
    "require": {
        "mrmarkfrench/silverpop-php-connector": "*"
    }
}
```

Please help.

**Comment by mrmarkfrench** [comment]
That's really strange. It sure looks like you have it right, and I haven't changed anything. Let me take a look and see if I can figure out what's going on.

**Comment by mrmarkfrench** [comment]
@rvarbanov, I think the issue is that you have set your Composer JSON file to require stable packages, and this package was classified as a dev package, so it refused to install it because it couldn't find a version flagged as stable. When this package was released, the default behavior in Composer was to accept dev packages, but that changed several versions ago.

I was able to install the package when I specified I wanted a dev version of it.

However, this package is not in a state of constant change, and hasn't been in some time. I've gone ahead and tagged version 1.2.3, which is now available for Composer to install. That version is flagged as stable.

You should be able to install the package simply by re-running `composer.phar update` in your local project.

**Comment by rvarbanov** [comment]
Thank you, I will try to install it again today

**Comment by rvarbanov** [comment]
Great, I was able to install it today.

Thank you very much for your support with that issue and for maintaining this repo!
